GET http://localhost:3000/subscribers

###


GET http://localhost:3000/subscribers/5fe75bfb59353225c70f

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Beno",
    "subscribedToChannel": "beno channel"

}

###
PATCH http://localhost:3000/subscribers/5fe75bdb59353225c70f1f16
Content-Type: application/json

{
    "name": "kweku",
    "subscribedToChannel": "kweku channel"
}



